version: 2

models:
    - name: stg_categories
      description: It contains all categories for products. One row per category.
      columns:
          - name: category_id
            description: The primary key of categories data.
            tests:
                - not_null
                - unique:
                    config: 
                      where: "category_name != 'Seafood'"
    - name: stg_orders
      description: It contains orders data. One row per order.
      columns:
          - name: order_id
            description: The primary key of orders data.
            tests:
                - not_null
                - unique
          - name: shipper_id
            tests:
              - relationships:
                  to: ref('stg_shippers')
                  field: shipper_id
              - accepted_values:
                  name: limited_shipper_reference
                  values: [1, 2, 3]
                  quote: false
    - name: stg_order_details
      description: It contains order details data. One row per order detail.
      config:
        elementary:
          timestamp_column: "ingested_at"  
      tests:
          - unique:
              column_name: "order_id || '-' || product_id"
          - elementary.volume_anomalies:
              name: elementary_volume_anomalies
              where_expression: "product_id != 0"
              time_bucket:
                period: hour
                count: 1
              training_period:
                period: hour
                count: 5
              detection_period:
                period: hour
                count: 1
              tags: ["elementary"]
              config:
                severity: warn
    - name: stg_products
      tests: 
        - dbt_utils.expression_is_true:
            name: test1_product_price_more_than_zero
            expression: "product_unit_price >= 0"
      columns:
          - name: product_id
            description: The primary key of products data.
            tests:
                - not_null
                - unique
          - name: product_unit_price
            tests:
              - dbt_expectations.expect_column_values_to_be_between: 
                  name: test2_product_price_more_than_zero
                  min_value: 0
                  row_condition: "product_id is not null" 
                  strictly: false
              - dbt_expectations.expect_column_mean_to_be_between: 
                  min_value: 1
                  strictly: false
    - name: stg_customers
      columns:
          - name: customer_id
            description: The primary key of customers data.
            tests:
                - not_null
                - unique
    - name: stg_suppliers
      columns:
          - name: supplier_id
            description: The primary key of suppliers data.
            tests:
                - unique
    - name: stg_shippers
      columns:
          - name: shipper_id
            description: The primary key of shippers data.
            tests:
                - unique
    - name: stg_employees
      columns:
          - name: employee_id
            description: The primary key of employees data.
            tests:
                - unique