st_dbt_project:
  outputs:
    dev:
      dataset: dataset_st_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: kering-onboarding
      threads: 1
      type: bigquery
  target: dev
